### ISSUE TITLE
extractor not validating any subreddits

### ISSUE THREAD

**Issue by pthomas4** [NSchrading/redditDataExtractor#10]
Hi - 

I'm hoping to download a specific subreddit's data (r/PoliticalDiscussion) but receive an error message each time I try to use the extractor.  Even the default subreddits produce a message "The subreddit does not exist."  Am I doing something wrong?

Thanks!

**Comment by NSchrading** [comment]
Closing - this project is no longer supported, as it has been deprecated due to reddit API changes for some time and is going to be archived.
