### ISSUE TITLE
Not able to download

### ISSUE THREAD

**Issue by hutchinsr** [NSchrading/redditDataExtractor#11]
I am trying to download files and get the error "to attempt to redownload this file, uncheck "restrict retrieved submissions to creation dates after the last downloaded submission" in the settings".  I have this setting unchecked but it will not download the files.

**Comment by annargrs** [comment]
Same here, tried on shortstories subreddit. It downloads a few items, fails on a few more, and gives up. Ubuntu 16.04, pre-compiled exe.linux-x86_64-3.4.

**Comment by ghost** [comment]
Yup it seems that this project has been forgotten.

**Comment by ghost** [comment]
But got the same problem

**Comment by rudolphos** [comment]
Yeah it's deprecated because of change of reddit API

https://www.reddit.com/r/changelog/comments/7tus5f/update_to_search_api/dtfcdn0/

**Comment by ProGamerGov** [comment]
Has anyone found a replacement to this project yet?

**Comment by ProGamerGov** [comment]
A new fork/similar project seems to still work: https://github.com/MalloyDelacroix/DownloaderForReddit

**Comment by NSchrading** [comment]
Closing - this project is no longer supported, as it has been deprecated due to reddit API changes for some time and is going to be archived.
