### ISSUE TITLE
Unrelated issue

### ISSUE THREAD

**Issue by Pyqtbroughtmehere** [NSchrading/redditDataExtractor#17]
Hey there mate, the guy who created this beautiful tool and posted it on Github.
You're the reason why i signed to Github to learn how to code.
Just yesterday i couldn't sleep  was thinking about this tool that i wanted to create that crawls a website gather links and download them, but i found yours the perfect one to start learning with, thing is im kind of a noob, new to this whole programing thing, i want to learn python.
I've installed python, installed pyqt4 that you provided, but the thing is on the line 24 it freezes.
 So i want to change that to pyqt5 because i had so many problems with pyqt4. 
if i do that will it affect the rest of the code. 
Edit = you know! after a second note this shit is fucking nerve breaking mate, you fix a problem another one pops out from the middle of nowhere, install fucking sip, oh wait sip doesn't work it need qt, install qt oh shit qt needs cs, cs needs pv, pv need dc, dc nneds ls, and when you do all that shit the program still won't work at the end, excuse my language, i don't have time for this shit, ... i need my smoke..

**Comment by NSchrading** [comment]
Closing - this project is no longer supported, as it has been deprecated due to reddit API changes for some time and is going to be archived.
