### ISSUE TITLE
Supported Downloader

### ISSUE THREAD

**Issue by MalloyDelacroix** [NSchrading/redditDataExtractor#18]
Since this project is no longer supported, I would like to make everyone aware of a similar project that is still under active development and support.

https://github.com/MalloyDelacroix/DownloaderForReddit

The Downloader For Reddit has a very similar UI, with many of the features requested here, and is updated in many ways.

**Comment by NSchrading** [comment]
Closing - this project is no longer supported, as it has been deprecated due to reddit API changes for some time and is going to be archived.
