### ISSUE TITLE
Videos not downloading

### ISSUE THREAD

**Issue by yada-yoda** [NSchrading/redditDataExtractor#20]
Videos seem to not download, instead "Uncheck Restrict retrieved submissions to creation dates after the last downloaded submission" error is logged; this is verified to be unchecked. Also, does this support redgifs.com hosted gifs and gifv as well?

**Comment by NSchrading** [comment]
Closing - this project is no longer supported, as it has been deprecated due to reddit API changes for some time and is going to be archived.
