### ISSUE TITLE
Top does not get top of all time

### ISSUE THREAD

**Issue by cidfire** [NSchrading/redditDataExtractor#5]
When choosing top as the sorting option, it only get the top post of less than a year. Is there a way to expand that to top from "all time"? I would like to archive a few now-dead sub-reddits and I don't want to get all the spam stuff and waste the 1000 post limit with "new".

**Comment by NSchrading** [comment]
Closing - this project is no longer supported, as it has been deprecated due to reddit API changes for some time and is going to be archived.
