### ISSUE TITLE
Fails to run, when installed on OSX.

### ISSUE THREAD

**Issue by jringloff** [NSchrading/redditDataExtractor#7]
Installed all the required bits, and it doesn't seem to work:

```
natasha:john(130:355)$ pwd
/Users/john/workarea/bin/redditDataExtractor-master
natasha:john(131:356)$ python3.4 main.py
Traceback (most recent call last):
  File "main.py", line 125, in <module>
    main()
  File "main.py", line 98, in main
    rddtDataExtractor._r.http.validate_certs = 'RedditDataExtractor/cacert.pem'
AttributeError: 'Reddit' object has no attribute 'http'
natasha:john(132:357)$ 
```

If I comment out line 98 or main.py, it runs, but all the default lists fail with a message every subreddit fails to exist.

`The subreddit movies does not exist. Remove from list?`
With a Yes|No dialog popup for each reddit list, I am using the defaults list to test.

Also had problems getting it to run without a praw.ini that included the client_id, once I had that, it ran, but didn't read the client_id, and I needed to re-enter in the extractor.

Any ideas? I am not a python guy, so I am operating outside my talent envelope here. But I have successfully installed dozens of other python apps without too many issues, well a file locking issue on one I was able to fix, and commit. This one has me stumped.

```
natasha:john(138:363)$ uname -a
Darwin natasha.wrongcrowd.net 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64
natasha:john(139:364)$ python3.4 -V
Python 3.4.6
natasha:john(139:364)$ pip3.4 list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
beautifulsoup4 (4.5.3)
pathlib (1.0.1)
pip (9.0.1)
praw (4.3.0)
prawcore (0.7.0)
requests (2.13.0)
setuptools (32.3.1)
update-checker (0.16)
youtube-dl (2015.7.4)
natasha:john(138:365)$ port installed | grep -E 'sip|pyqt'
  py-sip @4.19_0 (active)
  py27-sip @4.19_0 (active)
  py34-pyqt4 @4.12.0_0 (active)
  py34-sip @4.19_0 (active)
natasha:john(139:366)$ 
```

Anything I can do to gather more relevant info? The only runtime error I get when I comment out line 98 of main.py:

`libpng warning: iCCP: known incorrect sRGB profile`

Which would seem to me not relevant to the issues at hand.

**Comment by NSchrading** [comment]
Hi, sorry you've hit all these issues. I suspect the problem is that you are using the new, backwards-incompatible version of PRAW (v4+). When I wrote this, only PRAW v3 was around. Try downgrading to PRAW v3 (I think 3.4.0 or 3.5.0 is the latest). Hopefully that will fix it.

I'm not currently doing any development on this project (busy with other things), so I won't be updating the reddit data extractor to support the new version of PRAW in the foreseeable future.

**Comment by jringloff** [comment]
Returned to pristine state, loaded praw 3.5.0 working like a champ. I would suggest a note that it's not tested, or known to work with praw >3.5.0.
