### ISSUE TITLE
Not working for some images

### ISSUE THREAD

**Issue by wubalubadubdub1** [NSchrading/redditDataExtractor#8]
Using both the latest source version with the praw 3.5.0 downgrade, and the precompiled binaries for 64bit Linux Mint, some imgur images are not being downloaded properly. I keep getting a corrupted .gif file which   can't be opened by any image viewer or vlc.

For example, for the the image in this post, it doesn't work (corrupted .gif is downloaded)

https://www.reddit.com/r/reddit_data_extractor/comments/3c53r1/imgur_gifv_page/

**Comment by NSchrading** [comment]
Closing - this project is no longer supported, as it has been deprecated due to reddit API changes for some time and is going to be archived.
